### ISSUE TITLE
Just not working.

### ISSUE THREAD

**Issue by hasnogaems** [wkrueger/biggerbuffs#1]
I install it. Doesn't change anything. Also how i suppose to add "defensive, external or **custom** CDs on frames"?

**Comment by wkrueger** [comment]
Hello, mostly probably type `/bigger auto 1`, then reload.

As said in curse page, the addon wont load automatically until `/bigger start` is called on each section or `/bigger auto 1` is called.

Further talking, this was added because the addon will break raid frames if members join while in combat (requiring a reload)*. So if one plays mostly pugs he would type `/bigger start` when not in a pug.

Seeing this feature is a lot confusing, it'd be best if it just got removed. People including me will just tend to disable the addon when playing on pugs.

*this is not fixable. This is mostly why they just develop an entire raid frame addon instead of just changing the existing blizzard frames

**Comment by wkrueger** [comment]
made some updated today
